# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1db4de1f4a35cf30d4a0c6641ba94215c7141768a2ebf8d1c9856fef08a6a2ded2e1c9eb681e1c9b3a566fb997e514e0093f28da0139d20f23beeb9d0f84742

test:
  secret_key_base: c2ee6fa6a85b52fda105c7d49988d109a3ffda257c4da608a3a53d3b866dbe07d6003da81f5da106056416f7fe43f152cfa41797e83d32129a41e3f7fd7d1715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
